export const Eventsday = [
  {
    id: 1,
    imgURL: "/comingsoon.png",
    name: "DANCE SAGA",
    club: "Dance club",
    category: "Flagship",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 2,
    imgURL: "/comingsoon.png",
    name: "FOOTLOOSE",
    club: "Dance club",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 3,
    imgURL: "/comingsoon.png",
    name: "KBC: KOUN BANEGA COLLECTOR",
    club: "NAPS",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 4,
    imgURL: "/comingsoon.png",
    name: "BEYOND THE SCREEN - THE PRESS CONFERENCE",
    club: "NAPS",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 5,
    imgURL: "/comingsoon.png",
    name: "CIRCUIT CHASE",
    club: "ECESoc",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 6,
    imgURL: "/comingsoon.png",
    name: "ELECTRONICS BINGO",
    club: "ECESoc",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 7,
    imgURL: "/comingsoon.png",
    name: "ELECTRIC MONOPOLY",
    club: "ECESoc",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 8,
    imgURL: "/comingsoon.png",
    name: "SKYFALL SCRAMBLE",
    club: "AeroSoc",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 9,
    imgURL: "/comingsoon.png",
    name: "FLIGHT SIMULATION",
    club: "AeroSoc",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 10,
    imgURL: "/comingsoon.png",
    name: "BUSINESS CRISIS SIMULATION",
    club: "180DC",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 11,
    imgURL: "/comingsoon.png",
    name: "TIME TRAVELLER CONSULTANT",
    club: "180DC",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 12,
    imgURL: "/comingsoon.png",
    name: "BYTEHUNT",
    club: "EEESoc",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 13,
    imgURL: "/comingsoon.png",
    name: "WHERE IN BIT?",
    club: "IEEE",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 14,
    imgURL: "/comingsoon.png",
    name: "PITSTOP PIRSUIT",
    club: "Srijan",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 15,
    imgURL: "/comingsoon.png",
    name: "MISMATCHED",
    club: "Leo",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 16,
    imgURL: "/comingsoon.png",
    name: "TAKESHI'S CASTLE",
    club: "Leo",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 17,
    imgURL: "/comingsoon.png",
    name: "CINEMA CHESS CLASH",
    club: "IETE",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 18,
    imgURL: "/comingsoon.png",
    name: "BRIDGE THE GAP",
    club: "CES",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 19,
    imgURL: "/comingsoon.png",
    name: "PLANE CRASH",
    club: "CES",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 20,
    imgURL: "/comingsoon.png",
    name: "FOUNDER'S FACEOFF",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 21,
    imgURL: "/comingsoon.png",
    name: "NATSAMRAT",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 22,
    imgURL: "/comingsoon.png",
    name: "BITOTSAV QUIZ",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 23,
    imgURL: "/comingsoon.png",
    name: "KKK: KRAZY KAREN KUIZ",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 24,
    imgURL: "/comingsoon.png",
    name: "AURORA",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 25,
    imgURL: "/comingsoon.png",
    name: "ENIGNEERS ROAST BATTLE",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 26,
    imgURL: "/comingsoon.png",
    name: "BIT ROADIES",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 27,
    imgURL: "/comingsoon.png",
    name: "CAMPUS CAPITALIST",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 28,
    imgURL: "/comingsoon.png",
    name: "QUILL QUEST",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 29,
    imgURL: "/comingsoon.png",
    name: "KALAM-E-TAHIR",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 30,
    imgURL: "/comingsoon.png",
    name: "VALOMANIA",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 31,
    imgURL: "/comingsoon.png",
    name: "JUMANJI 3.O",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 32,
    imgURL: "/comingsoon.png",
    name: "SKYFALL SCRAMBLE",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 33,
    imgURL: "/comingsoon.png",
    name: "BEYOND THE SCREEN",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 34,
    imgURL: "/comingsoon.png",
    name: "EN CHESSANT",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 35,
    imgURL: "/comingsoon.png",
    name: "THE TALLEST",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 36,
    imgURL: "/comingsoon.png",
    name: "CYBERBRIGTON",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 37,
    imgURL: "/comingsoon.png",
    name: "TUG OF TORQUE",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 38,
    imgURL: "/comingsoon.png",
    name: "BLIND FURY:",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 39,
    imgURL: "/comingsoon.png",
    name: "INDUSTRIAL MAYHEM",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 40,
    imgURL: "/comingsoon.png",
    name: "SHARK TANK 2.O",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 41,
    imgURL: "/comingsoon.png",
    name: "LOST IN TRANSLATION",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 42,
    imgURL: "/comingsoon.png",
    name: "FOLK & FLAIR",
    club: "",
    category: "Formal",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 43,
    imgURL: "/comingsoon.png",
    name: "MR. AND MS. BITOTSAV",
    club: "",
    category: "Flagship",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 44,
    imgURL: "/comingsoon.png",
    name: "BATTLE OF BANDS",
    club: "",
    category: "Flagship",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 45,
    imgURL: "/comingsoon.png",
    name: "ABHINAY",
    club: "",
    category: "Flagship",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
  {
    id: 46,
    imgURL: "/comingsoon.png",
    name: "SQUID GAMES",
    club: "",
    category: "Flagship",
    description: "",
    venue: "TBD",
    time: "TBD",
    day: 1,
  },
];

export const Eventsnight = [
  {
    id: 200,
    name: "Heritage Night",
    description:
      "Experience the rich cultural heritage with traditional performances.",
    photo: "/revealing-soon.jpg",
  },
  {
    id: 201,
    name: "Band Night",
    description: "Enjoy electrifying live performances by top bands.",
    photo: "/revealing-soon.jpg",
  },
  {
    id: 202,
    name: "Dance Night",
    description:
      "Get ready for an energetic night of thrilling dance performances.",
    photo: "/revealing-soon.jpg",
  },
  {
    id: 203,
    name: "Pro Artist Night",
    description:
      "An unforgettable evening with renowned artists and performances.",
    photo: "/revealing-soon.jpg",
  },
];

export const clubs = [
  "ACM",
  "IEEE", //
  "SDS",
  "IET",
  "IETE", //
  "Robolution",
  "Aveon",
  "Firebolt",
  "Srijan", //
  "Dhwani",
  "Dance club", //
  "Ehsaas",
  "Spi-Macay",
  "Leo", //
  "Rotaract",
  "EPAC",
  "NAPS", //
  "PSoc",
  "IEI Civil",
  "IIChe",
  "EDC",
  "Finance",
  "180DC", //
  "AeroSoc", //
  "SIME",
  "LitSoc",
  "Unesquo",
  "BIOTS",
  "SAC",
  "FAS",
  "CES", //
  "ECESoc", //
  "EEESoc", //
  "Events Team",
];